---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: Wizard-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # You can pin to a specific version of Fedora as well

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - 7zip-standalone
        - btrfs-progs
        - cargo
        - distrobox
        - gamemode
        - gcc
        - gcc-c++
        - git
        - meson
        - ninja-build
        - nodejs22
        - podman
        - podman-compose
        - python3-pip
        - smartmontools
        - steam-devices
        - toolbox
        - micro
        - starship
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe
          - com.valvesoftware.Steam
          - com.discordapp.Discord
          - com.obsproject.Studio
          - com.usebottles.bottles
          - org.kde.kdenlive
          - net.blockbench.Blockbench
          - com.vysp3r.ProtonPlus
          - com.github.tchx84.Flatseal
          - com.mattjakeman.ExtensionManager
          - org.gnome.World.PikaBackup
          - org.localsend.localsend_app
          - org.gnome.Builder
          - io.github.flattool.Warehouse
          - com.ranfdev.DistroShelf
      - scope: user #Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
